version: '3.9'
services:
  stroke_api:
    build: ./API
    ports:
      - "8000:8000"
    networks:
      docker_network:
        ipv4_address: 172.29.1.1

  tests:
    build: ./Docker
    volumes:
      - ./my_volume:/shared_volume
    networks:
      docker_network:
        ipv4_address: 172.29.1.2
    environment: 
      LOG: "1"
    depends_on:
      - "stroke_api"

networks:
  docker_network:
      ipam:
         driver: default
         config:
            - subnet: 172.29.0.0/16
