# This workflow will install Python dependencies, run tests and lint

name: Control Push

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-20.04


    steps:
      - name: Checkout on master
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run tests
        run: |
          pytest
